spring.application.name=digital-payment
spring.datasource.url=jdbc:mysql://localhost:3306/payment_bank
spring.datasource.username=root
spring.datasource.password=****

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


